name: CI

on: [push, pull_request]

jobs:
  build-test-74:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6
        with:
          version: 2
          php_version: "7.4"

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9
          php_version: "7.4"
          configuration: phpunit.xml.dist
          bootstrap: vendor/autoload.php

  build-test-81:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6
        with:
          version: 2
          php_version: "8.1"

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9
          php_version: "8.1"
          configuration: phpunit.xml.dist
          bootstrap: vendor/autoload.php
